import { useTheme } from "next-themes";
import Head from "next/head";
import GrowSec from "../components/GrowSec";
import Header from "../components/Header";
import Navbar from "../components/Navbar";

export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <div>
      <Head>
        <title>Huddle Landing Page - joehsn</title>
        <meta
          name="description"
          content="Generated by create next app with ❤️ by joehsn"
        />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Navbar />
      <Header />
      <GrowSec />
      <footer>
        <div className="author bg-slate-900 text-white px-4 py-8">
          <span>
            Coded with ❤️ by{" "}
            <a href="https://linktr.ee/joehsn" target="_blank" rel="noreferrer">
              @joehsn
            </a>
            .
          </span>
          <select value={theme} onChange={(e) => setTheme(e.target.value)}>
            <option value="system">System</option>
            <option value="dark">Dark</option>
            <option value="light">Light</option>
          </select>
        </div>
      </footer>
    </div>
  );
}
